# Generated by Django 2.0.6 on 2020-10-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201028_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'other')], default='0', verbose_name='性别'),
        ),
    ]
