# Generated by Django 2.0.6 on 2020-10-30 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=22, verbose_name='用户名')),
                ('password', models.CharField(max_length=22, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=22, null=True, verbose_name='地址')),
                ('phone', models.CharField(max_length=22, null=True, verbose_name='手机号')),
                ('head_pic', models.ImageField(default='media/1.jpg', upload_to='media/%Y/%m', verbose_name='用户头像')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserDetail'),
        ),
    ]
